apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-mysql
  namespace: kubeflow
spec:
  volumeName: katib-mysql-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

