apiVersion: v1
kind: PersistentVolume
metadata:
  name: katib-mysql-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /exports/katib-mysql
    server: 10.65.191.254
